DROP TABLE IF EXISTS tbl_users;
DROP TABLE IF EXISTS tbl_files;

CREATE TABLE "tbl_users" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Username"	TEXT NOT NULL UNIQUE COLLATE RTRIM,
	"PasswordHash"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);

CREATE TABLE "tbl_files" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"FileName"	TEXT NOT NULL COLLATE RTRIM,
	"RelativePath"	TEXT NOT NULL COLLATE RTRIM,
	"Timestamp"	TEXT NOT NULL,
	"UserId"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT),
	FOREIGN KEY("UserId") REFERENCES "tbl_users"("Id")
);