DROP TABLE IF EXISTS tbl_config
DROP TABLE IF EXISTS tbl_users;
DROP TABLE IF EXISTS tbl_files;

CREATE TABLE "tbl_config" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE COLLATE RTRIM,
	"Value"	TEXT NOT NULL UNIQUE COLLATE RTRIM,
	PRIMARY KEY("Id" AUTOINCREMENT)
);

INSERT INTO tbl_config ("Name", "Value") VALUES ("root_folder", "");
INSERT INTO tbl_config ("Name", "Value") VALUES ("storage_limit", "");

CREATE TABLE "tbl_users" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Username"	TEXT NOT NULL UNIQUE COLLATE RTRIM,
	"PasswordHash"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);

CREATE TABLE "tbl_files" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"FileName"	TEXT NOT NULL COLLATE RTRIM,
	"RelativePath"	TEXT NOT NULL COLLATE RTRIM,
	"Timestamp"	TEXT NOT NULL,
	"UserId"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT),
	FOREIGN KEY("UserId") REFERENCES "tbl_users"("Id")
);